### PR TITLE
Add GitHub pages site (#6)

### PR DESCRIPTION
**Pull request by rickstaa**
This pull request introduces the deployment of our project's web page using GitHub Pages, a feature discussed in detail in issue #6. The primary goal of this feature is to enhance the visibility and accessibility of our project. You can view the deployed page at [https://rickstaa.dev/awesome-livepeer](https://rickstaa.dev/awesome-livepeer) to see the feature in action.

**Implementation**:

- Configured the repository to deploy the site using GitHub Pages using the [jerkyll-gh-pages.yml](https://github.com/rickstaa/awesome-livepeer/blob/main/.github/workflows/jekyll-gh-pages.yml) GitHub action.
- Added extra CI action to safeguard the quality of the list (i.e. https://github.com/rickstaa/awesome-livepeer/blob/main/.github/workflows/lint.yaml).
- Added extra release CI action which creates a new release when a new tag is pushed or the `bump:patch`, `bump:minor` or `bump:major` labels are attached to a PR (see https://github.com/rickstaa/awesome-livepeer/blob/44006f89e317c74e808fddfaa96fb5ce77b5cd17/.github/workflows/release.yml#L20C15-L20C20).
- Fixed awesome-lint errors.
- Added Logo.

**Testing**:

- Extensive testing has been conducted to ensure seamless integration and functionality. The live deployment successfully displays our project in a user-friendly web format.

**Next Steps**:

- Post-merge, we can link this page to the [https://livepeer.cool](https://livepeer.cool) domain. This will further enhance our project's visibility, particularly for those familiar with awesome lists.

**Repository Topics**:

- I recommend we add the `awesome` and `awesome-list` topics to our repository once this PR is merged. These topics will improve our project's discoverability on GitHub, aligning it with other curated lists and resources.

Feedback and further suggestions are welcome and highly appreciated 🚀.

### CODE REVIEW

**Comment by rickstaa** [comment]
Since I also fixed some linting errors, the easiest way to review this is by going through the commits individually, starting with https://github.com/livepeer/awesome-livepeer/pull/7/commits/50cfa08e03b38cfdd28a652aa63e807da58d7773 which contains the core of this pull request.

**Comment by rickstaa** [comment]
@dob It looks like the following websites no longer exist, have expired SSL certificates or are broken (see link checking CI -> https://github.com/rickstaa/awesome-livepeer/actions/runs/7684765006/job/20941777800).

https://github.com/livepeer/awesome-livepeer/blob/521ef9d0c75d4254fae477f3d5ea35e71af17454/README.md?plain=1#L9

https://github.com/livepeer/awesome-livepeer/blob/521ef9d0c75d4254fae477f3d5ea35e71af17454/README.md?plain=1#L107

https://github.com/livepeer/awesome-livepeer/blob/521ef9d0c75d4254fae477f3d5ea35e71af17454/README.md?plain=1#L126

I contacted the developers for a fix.

**Comment by rickstaa** [comment]
I temporarily broke the styling by adding the `livepeer.cool` domain. I will fix it later and let you know so you can check it out 👍🏻.

**Comment by rickstaa** [comment]
> I've temporarily disrupted the styling by integrating the `livepeer.cool` domain. I'm planning to address this issue shortly and will update you once it's resolved so you can take a look 👍🏻.

I fixed it 👍🏻. The website is now available at https://livepeer.cool. The certificate needs about 24 hours to update.

**Comment by dob** [comment]
Thanks @rickstaa. A couple small items...

1) On the output page it says something like, "This site is open source. Improve it here." I think it might be a little bit more inviting to community members to say something less dev centric and instead focus on the list. "This list is open source and maintained by the community. Suggest an improvement to add, edit, or remove items from Awesome Livepeer."

2) I didn't fully follow the version bump workflow. Will the page get updated when a change is merged into the README, or does someone have to also somehow bump a version to trigger a build?

**Review by iameli — APPROVED** [review]
Cool, this looks awesome to me! Do you have everything you need to make the GitHub workflows work? Are you able to test without merging? I know that can be a PITA

**Comment by rickstaa** [comment]
Hi @dob, thanks for sharing your insightful feedback!

> 1. On the output page it says something like, "This site is open source. Improve it here." I think it might be a little bit more inviting to community members to say something less dev centric and instead focus on the list. "This list is open source and maintained by the community. Suggest an improvement to add, edit, or remove items from Awesome Livepeer."

Regarding your first point about the website's footer message:

I completely agree that a more community-centric message would be more welcoming. The phrase "This list is open source and maintained by the community. Suggest an improvement to add, edit, or remove items from Awesome Livepeer" indeed sounds more inviting. I've initiated a pull request to address this, aiming to modify the default primer theme in a user-friendly manner. You can follow the progress of this request here: [GitHub PR link](https://github.com/pages-themes/primer/pull/85). Meanwhile, to expedite the launch of [https://livepeer.cool](https://livepeer.cool), we could consider the workaround detailed in Jake Lee's blog: [Removing GitHub Pages 'Improve this page'](https://blog.jakelee.co.uk/removing-github-pages-improve-this-page/).

> 2. I didn't fully follow the version bump workflow. Will the page get updated when a change is merged into the README, or does someone have to also somehow bump a version to trigger a build?

As for your second query about the version bump workflow:

The process is currently set up so that any merged pull request automatically updates the page. The workflow details are outlined here: [GitHub Workflow link](https://github.com/rickstaa/awesome-livepeer/blob/107497bff67009c8ddefffd30ae09df4db3d5ae8/.github/workflows/jekyll-gh-pages.yml#L6-L10). While versioning serves as a method for maintainers to keep track of changes, I'm open to suggestions for improvements. One idea is to trigger website updates only with new version releases, which could be more orderly if multiple collaborators exist.

Another possibility is using the [Release Please Action](https://github.com/google-github-actions/release-please-action) from GitHub, though it might be a bit complex for our needs. It automates changelogs and enforces the [conventional commits convention](https://www.conventionalcommits.org/en/v1.0.0/), as seen in this example: [Release tag link](https://github.com/rickstaa/stable-learning-control/releases/tag/v5.1.1).

Currently, our release action is simple and effective, especially considering that many contributors to [github.com/livepeer/awesome-livepeer](https://github.com/livepeer/awesome-livepeer) may not have a software development background. However, I'm eager to hear what you think about the best approach for our release workflow. Your feedback is greatly valued! 😃

**Comment by rickstaa** [comment]
Thanks, @iameli, for your encouragement 😃! The GitHub Actions are already operational in my fork, and the results are accessible at [https://livepeer.cool](https://livepeer.cool) (details can be found at [this link](https://github.com/rickstaa/awesome-livepeer/actions/runs/7698957899)). Integrating them into the main repository is straightforward; it just requires merging the pull request and adjusting the Cloudflare DNS settings.

You're right about the importance of testing changes without merging; it's essential for a smooth workflow. I haven't yet included instructions for this in our documentation, but I see the value in adding it to the [CONTRIBUTING.md](https://github.com/rickstaa/awesome-livepeer/blob/main/contributing.md) file, which follows the template from [https://github.com/jthegedus/awesome-list-template](https://github.com/jthegedus/awesome-list-template). To facilitate developer testing, we could consider several approaches:

1. **Local Jekyll Build**: Provide guidance on how to build and run the Jekyll page locally. This would allow developers to see their changes in real-time on their own machines.
2. **Docker Container**: Offer instructions for building and running the Jekyll environment using a provided Docker container. This could simplify setup and ensure a consistent environment across different systems.
3. **GitHub Action for PR Previews**: Develop a GitHub Action that automatically publishes changes from PRs to a temporary subdomain (e.g., livepeer.cool/PR323) and links this in the PR comments. This approach would enable easy viewing and testing of changes in a live environment before merging.

I'd love to hear which of these options you prefer, or if you have any other suggestions or preferences. Your feedback is invaluable in improving the development process!

**Comment by rickstaa** [comment]
@iameli, I've just conducted a swift investigation, and it appears that the native support for displaying PR page previews is not yet available within our GitHub action-based deploy pipeline. However, I have some good news! The GitHub team has already implemented this feature and is actively using it internally, as documented here: https://github.com/orgs/community/discussions/7730#discussioncomment-7603270. We can expect it to be deployed shortly.

In the meantime, I will update our CONTRIBUTING.md to provide clear instructions for maintainers on how to build the page locally or through a Docker container. This should help bridge the gap until the native support becomes available.

**Comment by rickstaa** [comment]
@iameli Since GitHub is actively developing a [GitHub Pages preview function](https://github.com/orgs/community/discussions/7730#discussioncomment-7603270), I believe we don't have to dedicate development resources to this task ourselves. In the meantime, I have updated the CONTRIBUTION.md to provide instructions on the local build process until GitHub officially releases this feature (see https://github.com/livepeer/awesome-livepeer/pull/7/commits/dee12a5c6f704400921bbf221f4d16f1f9b7bad6). 

@iameli, @dob If you have any suggestions for the [CONTRIBUTION.md](https://github.com/livepeer/awesome-livepeer/pull/7/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055 or the build procedure, please let me know 👍🏻.

**Comment by rickstaa** [comment]
@dob I've forked the build actions to allow us to set a custom footer in anticipation of https://github.com/pages-themes/primer/pull/85 being merged into the upstream. I've condensed your suggestion to keep it as a one-liner. If you have a new one-line footer idea, please share it. I believe we're ready to release livepeer.cool to the public. If you have any other changes you'd like me to make, please don't hesitate to reach out 😄.

**Pull request merged**
